### ISSUE TITLE
Setting up Ressource-Group/Virtual-Networks/VPN-Gateway "from scratch" fails: Error: Error: Resource Group "..." was not found

### ISSUE THREAD

**Issue by heitmanr** [kumarvna/terraform-azurerm-vpn-gateway#7]
When i start from scratch:
```
PS C:\TERRAFORM> terraform show

PS C:\TERRAFORM>
```
a terraform plan/apply with "main.tf" which contains everything (ressource-group, networks, etc. vpn-gateway) fails.

// i stripped down my original setup to a very basic Ressource-Group/Network/VPN-Gateway-Setup according to https://github.com/kumarvna/terraform-azurerm-vpn-gateway/tree/master/examples/site-to-site 
```
PS C:\TERRAFORM> cp .\main.tf-12_add_vpn-gateway.txt main.tf
```

```
PS C:\TERRAFORM> terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.vpn-gateway.data.azurerm_resource_group.rg: Refreshing state...

Warning: Interpolation-only expressions are deprecated

  on .terraform\modules\vpn-gateway\main.tf line 106, in resource "azurerm_virtual_network_gateway" "vpngw":
 106:   tags = merge({ "ResourceName" = "${var.vpn_gateway_name}" }, var.tags, )

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Error: Error: Resource Group "rg-shared-westeurope-01" was not found
  on .terraform\modules\vpn-gateway\main.tf line 4, in data "azurerm_resource_group" "rg":
   4: data "azurerm_resource_group" "rg" {


PS C:\TERRAFORM>
```

...the Resource-Group was not found - true - but is defined in the main.tf-file

- i'd expect this dependency to be resolved!?

When shortening the "main.tf"-file (File "..11..") - so it doesn't contain the "vpn-gateway"-object
* resource-group, networks, etc.
are successfully added.

When using afterwards the original "main.tf"-file "File "..12..") - containing the vpn-gateway
* the vpn-gateway 
is added, too.

A manual "depends"-hint inside the vpn-gateway-config isn't allowed.
[main.tf-11_setup_without_vpn-gateway.txt](https://github.com/kumarvna/terraform-azurerm-vpn-gateway/files/5569018/main.tf-11_setup_without_vpn-gateway.txt)
[main.tf-12_add_vpn-gateway.txt](https://github.com/kumarvna/terraform-azurerm-vpn-gateway/files/5569019/main.tf-12_add_vpn-gateway.txt)

**Comment by kumarvna** [comment]
Hi, 
This module except to provide the resource group, VNet and GatewaySubnet details as a variable or directly to the module arguments. The Module is looking for existing resource group and that's the reason you are seeing this error. Please use the following Module to create a required network environment first and then try to use this module with those values.  I have only provided values as an example, but you can use whatever name you want to create. Please go through the documentation provided as well for more details. 
While using the terraform it's only looking for the .tf files and use them to create a plan and create those resources if the plan is successful. there is no dependency on the name of the files. Hope this helps. 

To create VNet and Subnets: 
https://github.com/kumarvna/terraform-azurerm-vnet

**Comment by kumarvna** [comment]
I am closing this issue since I didn't get any further update. Please raise an issue if you still need any help.
